### ISSUE TITLE
Somes bugs

### ISSUE THREAD

**Issue by dudantas** [soul4soul/ot-monster-converter#14]
When converting the monsters, the "type" variable of the attack is being created only with "COMBAT_FIRE" and not "COMBAT_FIREDAMAGE"

Another observation is that the attack "melee" is being converted without "type" variable (in this case "COMBAT_PHYSICALDAMAGE")

PS: great tool. It was a great help. Congratulations.

https://github.com/opentibiabr/otservbr-global/pull/1676

**Comment by soul4soul** [comment]
Closed by #18
