### ISSUE TITLE
Add default header to generated tfs xml files

### ISSUE THREAD

**Issue by EPuncker** [soul4soul/ot-monster-converter#38]
`<?xml version="1.0" encoding="UTF-8"?>`
the one above

**Comment by soul4soul** [comment]
Thanks for the report. I need to verify it but removing this line should fix it.

https://github.com/soul4soul/ot-monster-converter/blob/51dcfc004c8dd71b65c964100cbfc06156d72b7c/app/MonsterConverterTfsXml/TfsXmlConverter.cs#L294
