### ISSUE TITLE
Getting monster outfit from staticdata.xml file possible?

### ISSUE THREAD

**Issue by EPuncker** [soul4soul/ot-monster-converter#40]
I've got a file with all monsters that are present in bestiary and their respective looktypes up to version 12.30

https://pastebin.com/NSi5DE2Z

and I'm wondering if it would be useful to your project somehow to get monster looktype by name 😃

**Comment by soul4soul** [comment]
For demonstration purposes here is an updated version of the TibiaWiki converter using the hard coded outfit data you provided. https://gist.github.com/soul4soul/155013260db87c09f048d2c3d360227e

Another approach we can take working with TibiaWiki is to make a page of outfits similar to what they did for https://tibia.fandom.com/wiki/Effects. The page could contain a gif of the outfit, update implemented, common outfit name, outfit id, and optional list of monsters in game using the outfit. This is less ambitious and the information wouldn't be as complete but it will still help to set many monster look types.

**Comment by EPuncker** [comment]
updated file with up to 12.86 update outfits
[outfits.txt](https://github.com/soul4soul/ot-monster-converter/files/8666695/outfits.txt)
