### ISSUE TITLE
Two minor suggestions regarding xml files

### ISSUE THREAD

**Issue by EPuncker** [soul4soul/ot-monster-converter#55]
- add new line at end of file
- make it utf-8 without BOM

just to keep a little of consistency with tfs files

an optional thing:
- make file names like_this.xml instead of Like This.xml (but this one can be easily done by anyone)

**Comment by soul4soul** [comment]
> 
> 
>     * add new line at end of file
I checked and didn't find a solution using XmlWriter by default and I don't think it's worth while to write each file, open it, read it back, add a new line, and write again for a new line.

>     * make it utf-8 without BOM
Done in 064dd52

>     * make file names like_this.xml instead of Like This.xml (but this one can be easily done by anyone)
The file name is determined by the input file name, the code keeps the same naming and formatting and only the extension is changed. `like_this.xml` -> `like_this.lua` and `Like This.xml` -> `Like This.lua`. For TibiaWiki file name I use the name of the page on tibiawiki so it's usually `Like_This` and in other formats the extension is added `Like_This.xml`. In #52 I fixed an issue where I wasn't setting the correct file name for tibiaiwiki.
