### ISSUE TITLE
[question] Woud be posible to make a converter but for npcs?

### ISSUE THREAD

**Issue by especialized-oldschoool** [soul4soul/ot-monster-converter#69]
Hi as title says.
i have converted cipsoft monster  to lua with this tool and they are working pretty cool
i wonder if you will or would release a tool to convert npcs from cipsoft to lua tried with this tool if its possible and at the momment it's not :( would be great if it could  convert npcs to tfs revscripts or similar
and thank you in advance for this great tool

regards

**Comment by soul4soul** [comment]
Yes it is possible but not something I'm interested in working on. Thanks for the kind comments about the monster converter.
